apiVersion: v1
kind: Secret
metadata:
  name: github-authentication
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: nmasse-itix
  password: '__GITHUB_TOKEN__'

