apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: demo-appdev-initial
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  serviceAccountName: tekton-robot
  pipelineRef:
    name: demo-appdev
  params:
  - name: gitRepositoryURL
    value: https://github.com/nmasse-itix/demo-appdev.git
  - name: outputContainerImage
    value: image-registry.openshift-image-registry.svc:5000/demo-appdev/function
  workspaces:
  - name: scratch
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
